FORMAT: 1A
HOST: http://localhost:5000/

# Storekeeper

Storekeeper allows dataexchange between a DCS mission and a persistant backend API.

# Group / 
This is the API root endpoint. It accepts GET and POST requests

## GET [/api/v1/]

### GET
Simple endpoint to check that the API is up and available
    + Response 200 (application/json)
        { "msg": "Storekeeper API is running!" }

## POST [/api/v1/]

### POST
Mirrors the request posted back
    + Response 200 (application/json)
        { "header": { "content-type": "application/x-www-form-urlencoded", "user-agent": ... }}

# Group /airports
This endpoint provides a list of all airports in DCS with some associated data

## GET [/api/v1/airports{?limit}]

### GET 
    + Parameters
        + limit (number, optional) - The maximum number of results to return
            + Default: 'all'