FORMAT: 1A

// https://apiblueprint.org/documentation/tutorial.html

# Storekeeper

Storekeeper is allows dataexchange between a DCS mission and a persistant backend API.

# Group Public

## Root Endpoint [/api/v1/]

### Hello World [GET]
Simple endpoint to check that the API is up and available

+ Response 200 (application/json)
    { "msg": "Storekeeper API is running!" }

### Echo Request [POST]
Mirrors the request posted back

+ Response 200 (application/json)
    { "header": { "content-type": "application/x-www-form-urlencoded", "user-agent": ... }}