FORMAT: 1A

// https://apiblueprint.org/documentation/tutorial.html

# Storekeeper

Storekeeper is allows dataexchange between a DCS mission and a persistant backend API.

## Root Endpoint [/api/v1/]

### Hello World [GET]
+ Response 200 (application/json)
[
  {
    msg: 'Helllo World!'
  }
]