name: Node CI - Tests Only

on: [push, pull_request]

env:
  PORT: 5000
  ROOT_URL: ROOT_URL=/api/v1

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [8.x, 10.x, 12.x]
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          { echo 'PORT=5000'; echo 'ROOT_URL=/api/v1';} >> .env
          npm i
          npm ci
          # npm run build --if-present
          npm test
        env:
          CI: true
